export const allChurchOfficers = {
    "categories": [
       "Church Elders" ,
       "DEACONATE" ,
       "SECRETARY CHURCH" ,
       "CHURCH TREASURERS" ,
       "SABBATH SCHOOL" ,
       "EVANGELISM" ,
       "PUBLISHING" ,
       "ADVENTIST YOUTH" ,
       "Pathfinder Club" ,
       "Adventurer Club" ,
       "Ambassador Club" ,
       "STEWARDSHIP" ,
       "TRUST SERVICE" ,
       "HEALTH MINISTRIES" ,
       "DORCAS" ,
       "CONSTRUCTION" ,
       "MIFEM" ,
       "MUSIC" ,
       "PUBLIC AFFAIRS & RELIGIOUS LIBERTY" ,
       "COMMUNICATION" ,
       "MEDIA & SOCIAL NETWOK" ,
       "PROJECTION" ,
       "AUDITING" ,
       "SOUND SYSTEM" ,
       "SMALL GROUPS" ,
       "CHILDREN" ,
       "Trainers" ,
       "FAMILY" ,
       "AMO" ,
       "ADVENTIST POSSIBILITY MINISTRIES" ,
       "EDUCATION" ,
       "INTEREST COORDINATORS" ,
       "DEACONS" ,
       "DEACONESSES" ,
       "Elder",
       "DEPARTEMENT",
       "SMALL GROUP LEADERS" 
    ]
  }
  